export interface BlogArticle {
  slug: string;
  title: string;
  pill: string; // judul singkat untuk carousel/teaser (LembarGuruApp.tsx)
  excerpt: string;
  category: string;
  date: string; // ISO
  content: string[]; // paragraf/heading, dirender apa adanya per baris
}

export const BLOG_ARTICLES: BlogArticle[] = [
  {
    slug: 'kiat-sukses-mendidik-generasi-sekarang',
    title: '7 Kiat Sukses Mendidik Generasi Sekarang',
    pill: 'Kiat Sukses Mendidik',
    excerpt: 'Siswa hari ini tumbuh dengan gawai di tangan dan informasi yang datang dari segala arah. Berikut pendekatan yang terbukti efektif untuk mendidik mereka tanpa kehilangan wibawa maupun koneksi.',
    category: 'Kiat Mendidik',
    date: '2026-06-02',
    content: [
      'Mendidik siswa generasi sekarang membutuhkan pendekatan yang berbeda dari satu dekade lalu. Mereka terbiasa dengan informasi instan, tapi justru karena itu mereka butuh figur guru yang bisa membimbing cara berpikir, bukan sekadar menyampaikan materi.',
      '## 1. Bangun hubungan sebelum menuntut hasil',
      'Siswa yang merasa dipahami akan jauh lebih terbuka menerima arahan, termasuk kritik. Luangkan waktu di awal semester untuk mengenal minat dan latar belakang siswa, bukan langsung masuk ke materi.',
      '## 2. Jelaskan alasan di balik aturan',
      'Generasi sekarang jarang patuh hanya karena "kata guru". Mereka lebih kooperatif kalau paham kenapa sebuah aturan atau tugas itu penting untuk mereka, bukan cuma untuk memenuhi kurikulum.',
      '## 3. Beri ruang untuk salah',
      'Rasa takut salah sering membuat siswa diam di kelas. Ciptakan suasana di mana kesalahan adalah bagian normal dari belajar, bukan sesuatu yang memalukan.',
      '## 4. Manfaatkan teknologi, jangan melawannya',
      'Daripada melarang gawai sepenuhnya, arahkan penggunaannya untuk hal produktif: riset cepat, kuis interaktif, atau kolaborasi tugas kelompok.',
      '## 5. Konsisten, bukan keras',
      'Ketegasan yang konsisten jauh lebih efektif daripada sesekali marah besar. Siswa belajar dari pola, bukan dari ledakan emosi sesaat.',
      '## 6. Rayakan progres kecil',
      'Tidak semua siswa akan langsung menonjol. Mengapresiasi kemajuan kecil membangun motivasi jangka panjang yang jauh lebih tahan lama dibanding tekanan nilai semata.',
      '## 7. Jaga diri sendiri',
      'Guru yang kelelahan sulit memberi yang terbaik. Kelola waktu dan energi supaya bisa hadir penuh untuk siswa, bukan sekadar menyelesaikan jam mengajar.',
    ],
  },
  {
    slug: 'cara-mengajar-efektif-di-kelas-besar',
    title: 'Cara Mengajar Efektif di Kelas dengan Jumlah Siswa Besar',
    pill: 'Cara Mengajar Efektif',
    excerpt: 'Mengelola 30-40 siswa sekaligus bukan perkara mudah. Berikut strategi praktis supaya pembelajaran tetap efektif meski kelas penuh sesak.',
    category: 'Cara Mengajar',
    date: '2026-06-10',
    content: [
      'Kelas dengan jumlah siswa besar sering membuat interaksi personal terasa mustahil. Padahal dengan strategi yang tepat, keterbatasan ini bisa disiasati tanpa mengorbankan kualitas pembelajaran.',
      '## Bagi kelas jadi kelompok kecil',
      'Diskusi dalam kelompok 4-5 orang jauh lebih efektif daripada diskusi satu kelas penuh. Setiap siswa punya kesempatan lebih besar untuk bicara dan terlibat aktif.',
      '## Gunakan sistem giliran yang jelas',
      'Alih-alih menunjuk siswa secara acak (yang sering hanya mengenai segelintir siswa aktif), buat sistem giliran tersistematis supaya semua siswa mendapat kesempatan yang sama untuk merespons.',
      '## Manfaatkan penilaian sebaya (peer assessment)',
      'Melibatkan siswa untuk saling menilai tugas sederhana (dengan rubrik yang jelas) meringankan beban koreksi guru sekaligus melatih siswa berpikir kritis.',
      '## Siapkan instruksi tertulis, bukan hanya lisan',
      'Di kelas besar, instruksi lisan mudah tidak terdengar oleh siswa di baris belakang. Tuliskan instruksi utama di papan tulis atau bagikan lembar kerja agar semua siswa punya rujukan yang sama.',
      '## Manfaatkan "zona kerja" di kelas',
      'Atur area tertentu untuk kerja mandiri, area lain untuk diskusi kelompok. Pengaturan fisik ini membantu mengelola kebisingan dan fokus tanpa harus terus-menerus menegur.',
    ],
  },
  {
    slug: 'menghadapi-berbagai-sifat-siswa-di-kelas',
    title: 'Cara Menghadapi Berbagai Sifat Siswa di Kelas',
    pill: 'Menghadapi Sifat Siswa',
    excerpt: 'Dari siswa pendiam hingga yang paling ramai, setiap karakter butuh pendekatan berbeda. Kenali pola umum dan cara meresponsnya secara efektif.',
    category: 'Manajemen Kelas',
    date: '2026-06-18',
    content: [
      'Satu kelas biasanya berisi siswa dengan karakter yang sangat beragam. Memaksakan satu pendekatan untuk semua justru sering memperbesar masalah, bukan menyelesaikannya.',
      '## Siswa pendiam',
      'Jangan buru-buru menganggap siswa pendiam sebagai tidak paham atau tidak peduli. Beri ruang untuk merespons lewat tulisan atau diskusi kelompok kecil, sebelum diminta bicara di depan kelas.',
      '## Siswa yang mendominasi diskusi',
      'Apresiasi antusiasmenya, tapi tetapkan aturan giliran bicara yang jelas supaya siswa lain juga dapat kesempatan. Bisa juga diberi peran khusus, misalnya sebagai moderator kelompok.',
      '## Siswa yang mudah bosan dan mengganggu',
      'Sering kali ini sinyal bahwa materi terlalu mudah atau metode penyampaian kurang variatif. Coba selingi dengan aktivitas yang lebih menantang atau berbasis gerak.',
      '## Siswa yang cemas berlebihan pada ujian',
      'Bantu dengan memecah target besar jadi target kecil yang lebih mudah dicapai, dan berikan umpan balik yang menekankan proses, bukan hanya nilai akhir.',
      '## Siswa yang sering menantang otoritas guru',
      'Hindari konfrontasi di depan kelas yang bisa memperbesar ego kedua belah pihak. Ajak bicara empat mata, dengarkan alasan di baliknya, baru tetapkan batasan yang jelas.',
      '## Kuncinya: observasi sebelum bereaksi',
      'Sebelum menegur atau mengambil tindakan, coba pahami dulu pola perilaku dan kemungkinan penyebabnya. Respons yang tepat sasaran jauh lebih efektif daripada respons yang cepat tapi asal.',
    ],
  },
  {
    slug: 'menyusun-rpp-yang-benar-benar-terpakai',
    title: 'Menyusun RPP yang Benar-Benar Terpakai, Bukan Sekadar Administrasi',
    pill: 'Menyusun RPP Efektif',
    excerpt: 'RPP sering jadi beban administratif yang dibuat asal jadi. Padahal RPP yang baik justru mempermudah guru saat mengajar. Ini caranya.',
    category: 'Cara Mengajar',
    date: '2026-06-24',
    content: [
      'Banyak guru menyusun RPP hanya untuk memenuhi kewajiban administratif, lalu tidak pernah membukanya lagi saat mengajar. Padahal RPP yang disusun dengan baik seharusnya jadi alat bantu nyata di kelas.',
      '## Mulai dari tujuan, bukan dari kegiatan',
      'Tentukan dulu apa yang harus bisa dilakukan siswa di akhir pembelajaran, baru rancang kegiatan yang benar-benar mengarah ke sana — bukan sebaliknya.',
      '## Buat singkat dan mudah dibaca sekilas',
      'RPP yang terlalu panjang justru jarang dibuka lagi saat mengajar. Format ringkas dengan poin-poin kunci jauh lebih praktis dipakai di tengah kesibukan kelas.',
      '## Sertakan rencana cadangan',
      'Materi tidak selalu berjalan sesuai rencana. Siapkan alternatif kegiatan singkat untuk kondisi kelas yang lebih cepat atau lebih lambat dari perkiraan.',
      '## Sesuaikan dengan kondisi kelas, bukan kelas ideal',
      'RPP yang disalin mentah dari contoh sering tidak cocok dengan kondisi siswa sesungguhnya. Sesuaikan tingkat kesulitan dan durasi dengan karakteristik kelas yang benar-benar dihadapi.',
    ],
  },
  {
    slug: 'membangun-motivasi-belajar-siswa',
    title: 'Membangun Motivasi Belajar Siswa yang Tahan Lama',
    pill: 'Membangun Motivasi Belajar',
    excerpt: 'Motivasi yang dibangun dari rasa takut nilai jelek cenderung cepat pudar. Berikut cara menumbuhkan motivasi belajar yang lebih tahan lama.',
    category: 'Kiat Mendidik',
    date: '2026-07-01',
    content: [
      'Motivasi belajar yang hanya bersumber dari rasa takut (takut nilai jelek, takut dimarahi) cenderung hilang begitu tekanan itu tidak ada lagi. Motivasi yang lebih tahan lama biasanya tumbuh dari rasa relevan dan rasa mampu.',
      '## Kaitkan materi dengan kehidupan nyata siswa',
      'Siswa lebih termotivasi belajar sesuatu yang terasa relevan dengan hidup mereka. Tunjukkan contoh konkret bagaimana materi dipakai di luar kelas.',
      '## Beri tantangan yang pas, jangan terlalu mudah atau sulit',
      'Tugas yang terlalu mudah terasa membosankan; yang terlalu sulit membuat siswa menyerah lebih dulu. Cari titik tengah yang membuat siswa merasa tertantang tapi tetap yakin bisa berhasil.',
      '## Berikan umpan balik spesifik, bukan sekadar angka',
      'Nilai angka saja tidak memberi tahu siswa apa yang harus diperbaiki. Umpan balik yang spesifik membantu mereka melihat jalan untuk berkembang.',
      '## Libatkan siswa dalam menentukan target belajarnya',
      'Siswa yang ikut menentukan targetnya sendiri (bukan cuma menerima target dari guru) cenderung merasa lebih bertanggung jawab untuk mencapainya.',
    ],
  },
  {
    slug: 'trik-belajar-cepat-dan-efektif',
    title: '7 Trik Belajar Cepat dan Efektif yang Terbukti Ilmiah',
    pill: 'Trik Belajar Cepat',
    excerpt: 'Belajar lama bukan berarti belajar efektif. Berikut teknik belajar yang didukung riset dan bisa langsung dicoba siswa mulai hari ini.',
    category: 'Tips Belajar Siswa',
    date: '2026-07-03',
    content: [
      'Banyak siswa menghabiskan berjam-jam membaca ulang catatan tapi tetap lupa saat ujian. Masalahnya bukan kurang waktu belajar, tapi caranya yang kurang efektif. Berikut beberapa teknik yang terbukti lebih hasil-guna dibanding sekadar membaca berulang.',
      '## 1. Active recall, bukan membaca ulang',
      'Daripada membaca ulang materi, coba tutup buku dan tulis kembali apa yang masih diingat. Proses mengingat aktif ini jauh lebih efektif memperkuat memori dibanding membaca pasif berkali-kali.',
      '## 2. Spaced repetition',
      'Ulangi materi dengan jeda waktu yang makin panjang (misalnya hari ini, besok, tiga hari lagi, seminggu lagi) alih-alih belajar maraton semalam sebelum ujian. Otak lebih kuat menyimpan informasi yang diulang secara berkala.',
      '## 3. Teknik Feynman: ajarkan ke orang lain',
      'Coba jelaskan materi dengan bahasa sederhana seolah-olah mengajari adik kelas. Bagian yang terasa sulit dijelaskan biasanya adalah bagian yang sebenarnya belum benar-benar dipahami.',
      '## 4. Pomodoro: fokus dalam blok pendek',
      'Belajar 25 menit penuh fokus, istirahat 5 menit, ulangi. Blok waktu pendek dengan jeda membantu menjaga konsentrasi dibanding belajar berjam-jam tanpa henti yang justru menurunkan fokus.',
      '## 5. Kaitkan materi baru dengan yang sudah dipahami',
      'Informasi baru lebih mudah menempel kalau dikaitkan dengan sesuatu yang sudah diketahui. Cari analogi atau contoh dari kehidupan sehari-hari untuk konsep yang terasa abstrak.',
      '## 6. Variasikan tempat dan cara belajar',
      'Belajar di tempat yang sama dengan cara yang sama terus-menerus membuat memori terlalu bergantung pada konteks itu. Sesekali ganti suasana atau format belajar (menulis, diagram, rekaman suara) supaya ingatan lebih fleksibel.',
      '## 7. Cukup tidur, jangan begadang',
      'Konsolidasi memori terjadi saat tidur. Belajar maraton semalaman sambil mengorbankan jam tidur justru membuat otak lebih sulit menyimpan apa yang baru dipelajari.',
    ],
  },
  {
    slug: 'cara-mengatur-waktu-belajar-siswa',
    title: 'Cara Mengatur Waktu Belajar Supaya Tidak Keteteran Menjelang Ujian',
    pill: 'Mengatur Waktu Belajar',
    excerpt: 'Menumpuk semua materi di malam terakhir sebelum ujian nyaris selalu berujung stres. Berikut cara mengatur waktu belajar yang lebih realistis.',
    category: 'Tips Belajar Siswa',
    date: '2026-07-04',
    content: [
      'Banyak siswa baru mulai belajar serius beberapa hari sebelum ujian, lalu kewalahan karena materi menumpuk. Mengatur waktu belajar sejak awal jauh lebih ringan daripada mengejar ketertinggalan di menit-menit akhir.',
      '## Buat jadwal mingguan, bukan cuma harian',
      'Lihat gambaran besar dulu: mapel apa saja yang perlu dipelajari minggu ini, dan berapa banyak waktu yang realistis bisa dialokasikan. Baru pecah jadi jadwal harian yang lebih detail.',
      '## Dahulukan materi yang paling sulit',
      'Kerjakan materi yang paling menantang saat energi dan fokus masih tinggi (biasanya di awal sesi belajar), bukan ditunda ke akhir saat sudah lelah.',
      '## Sisihkan waktu untuk mengulang, bukan cuma materi baru',
      'Jadwal yang cuma diisi materi baru terus-menerus membuat materi lama terlupakan. Sisihkan sebagian waktu tiap minggu khusus untuk mengulang apa yang sudah dipelajari sebelumnya.',
      '## Pecah tugas besar jadi langkah kecil',
      'Tugas atau target belajar yang besar terasa berat kalau dilihat sekaligus. Pecah jadi langkah-langkah kecil dengan tenggat masing-masing supaya progresnya terasa dan tidak menumpuk di akhir.',
      '## Beri jeda istirahat yang sesungguhnya',
      'Istirahat sambil scroll media sosial sering tidak benar-benar memulihkan energi. Coba istirahat dengan aktivitas yang benar-benar melepaskan pikiran dari layar, seperti jalan kaki singkat atau meregangkan badan.',
    ],
  },
  {
    slug: 'tips-menjadi-guru-pemula-percaya-diri',
    title: 'Tips Menjadi Guru Pemula yang Percaya Diri di Depan Kelas',
    pill: 'Tips Menjadi Guru',
    excerpt: 'Hari pertama mengajar sering terasa menegangkan, bahkan untuk yang sudah siap secara materi. Berikut cara membangun rasa percaya diri di depan kelas.',
    category: 'Tips Menjadi Guru',
    date: '2026-07-06',
    content: [
      'Rasa grogi di hari-hari pertama mengajar itu wajar, bahkan dialami hampir semua guru berpengalaman waktu masih pemula. Yang membedakan bukan tidak pernah gugup, tapi tahu cara mengelolanya supaya tidak mengganggu performa di kelas.',
      '## Kuasai 10 menit pertama',
      'Kesan awal di 10 menit pertama sering menentukan suasana sepanjang jam pelajaran. Siapkan pembuka yang jelas dan terlatih — tidak perlu rumit, cukup yang membuat guru terlihat tenang dan siap.',
      '## Wibawa dibangun dari konsistensi, bukan suara keras',
      'Siswa lebih menghormati guru yang konsisten dengan aturan dan janjinya, bukan yang paling galak. Tetapkan batasan yang jelas sejak awal dan jalankan secara konsisten.',
      '## Wajar tidak tahu semua jawaban',
      'Guru pemula sering takut terlihat tidak kompeten kalau tidak bisa jawab pertanyaan siswa. Padahal jujur mengatakan "saya cek dulu, nanti saya jawab" jauh lebih membangun kepercayaan daripada berpura-pura tahu.',
      '## Siapkan rencana cadangan',
      'Rasa percaya diri sering runtuh saat rencana mengajar tidak berjalan sesuai perkiraan. Siapkan alternatif kegiatan singkat untuk kondisi kelas yang lebih cepat atau lebih lambat dari perkiraan, supaya tidak panik di tengah jalan.',
      '## Belajar dari guru senior, tapi temukan gaya sendiri',
      'Amati cara mengajar guru yang lebih berpengalaman, tapi jangan memaksakan gaya yang tidak sesuai dengan kepribadian sendiri. Siswa bisa merasakan kalau seorang guru tidak nyaman dengan caranya sendiri.',
      '## Refleksi setelah tiap kelas, jangan cuma menilai diri sendiri',
      'Setelah mengajar, catat apa yang berjalan baik dan apa yang perlu diperbaiki — bukan untuk menghakimi diri sendiri, tapi supaya ada progres nyata dari waktu ke waktu.',
    ],
  },
  {
    slug: 'mengembangkan-karier-sebagai-guru',
    title: 'Cara Mengembangkan Karier sebagai Guru di Luar Mengajar di Kelas',
    pill: 'Mengembangkan Karier Guru',
    excerpt: 'Profesi guru punya banyak jalur pengembangan di luar rutinitas mengajar harian. Berikut beberapa arah yang bisa mulai dijajaki.',
    category: 'Tips Menjadi Guru',
    date: '2026-07-07',
    content: [
      'Banyak guru merasa kariernya "mentok" begitu-begitu saja setiap tahun. Padahal profesi guru punya banyak jalur pengembangan yang jarang disadari, di luar sekadar naik jam mengajar atau menunggu jadi kepala sekolah.',
      '## Ikut komunitas dan pelatihan guru',
      'Komunitas guru (daring maupun luring) jadi tempat bertukar metode mengajar, materi, dan dukungan moral. Banyak juga pelatihan gratis atau bersubsidi yang bisa memperkaya kompetensi tanpa biaya besar.',
      '## Kembangkan kompetensi digital',
      'Guru yang terbiasa memakai alat bantu digital untuk menyusun materi, soal, dan penilaian punya nilai tambah signifikan, terutama di sekolah yang terus mendorong transformasi digital.',
      '## Jadi penulis modul atau materi ajar',
      'Pengalaman mengajar bertahun-tahun adalah modal berharga untuk menulis modul, buku ajar, atau konten edukasi. Ini bisa jadi jalur penghasilan tambahan sekaligus memperluas dampak di luar kelas sendiri.',
      '## Ikut lomba inovasi pembelajaran',
      'Banyak kompetisi karya inovasi pembelajaran tingkat sekolah, daerah, hingga nasional. Selain pengakuan, proses menyusun karya inovasi juga mendorong guru terus bereksperimen dengan metode baru.',
      '## Jajaki peran mentor atau pembina guru baru',
      'Mendampingi guru yang lebih baru tidak cuma membantu mereka, tapi juga melatih kemampuan kepemimpinan yang berguna kalau suatu saat ingin mengambil peran struktural.',
    ],
  },
  {
    slug: 'panduan-orang-tua-mendampingi-anak-belajar',
    title: 'Panduan Orang Tua Mendampingi Anak Belajar di Rumah Tanpa Drama',
    pill: 'Panduan Orang Tua',
    excerpt: 'Mendampingi anak belajar di rumah sering berujung emosi naik, baik dari orang tua maupun anak. Berikut cara mendampingi yang lebih tenang dan efektif.',
    category: 'Panduan Orang Tua',
    date: '2026-07-08',
    content: [
      'Niat baik mendampingi anak belajar di rumah sering berubah jadi pertengkaran kecil karena cara pendekatannya kurang tepat. Berikut beberapa cara mendampingi yang lebih tenang, tanpa mengorbankan hubungan dengan anak.',
      '## Buat rutinitas, bukan cuma aturan dadakan',
      'Anak lebih mudah menerima waktu belajar yang sudah jadi rutinitas harian dibanding perintah mendadak "ayo belajar sekarang". Sepakati bersama jam belajar yang konsisten setiap hari.',
      '## Dampingi, jangan mengambil alih',
      'Godaan untuk langsung membetulkan atau mengerjakan tugas anak itu besar, apalagi kalau melihat anak kesulitan. Tapi anak belajar justru dari proses mencoba dan salah — peran orang tua lebih ke mengarahkan, bukan menggantikan.',
      '## Jangan cuma fokus ke nilai akhir',
      'Terlalu menekankan nilai membuat anak takut salah dan menghindari tantangan. Apresiasi juga usaha dan proses belajarnya, bukan cuma angka di rapor.',
      '## Kelola emosi diri sendiri dulu',
      'Rasa frustrasi orang tua sering lebih cepat meningkat daripada anaknya sendiri. Kalau mulai emosi, lebih baik jeda sebentar daripada melanjutkan sesi belajar dalam suasana tegang.',
      '## Komunikasi rutin dengan guru di sekolah',
      'Guru punya gambaran perkembangan anak dari sisi yang mungkin tidak terlihat di rumah. Komunikasi rutin membantu orang tua memberi dukungan yang lebih tepat sasaran, bukan menerka-nerka sendiri.',
    ],
  },
  {
    slug: 'tanda-anak-butuh-bantuan-belajar-tambahan',
    title: '5 Tanda Anak Butuh Bantuan Belajar Tambahan dan Cara Mendukungnya',
    pill: 'Tanda Anak Butuh Bantuan',
    excerpt: 'Tidak semua anak akan bicara terus terang kalau kesulitan mengikuti pelajaran. Kenali tanda-tandanya sebelum semakin tertinggal.',
    category: 'Panduan Orang Tua',
    date: '2026-07-09',
    content: [
      'Anak tidak selalu bisa mengungkapkan dengan jelas kalau sedang kesulitan mengikuti pelajaran di sekolah. Mengenali tanda-tandanya lebih awal membantu orang tua memberi dukungan sebelum masalahnya makin menumpuk.',
      '## 1. Nilai menurun bertahap, bukan tiba-tiba',
      'Penurunan nilai yang bertahap di satu mapel tertentu sering jadi sinyal awal ada konsep dasar yang belum benar-benar dipahami, bukan sekadar kurang belajar semalam sebelum ujian.',
      '## 2. Menghindari tugas mapel tertentu',
      'Anak yang selalu menunda atau mencari alasan untuk tidak mengerjakan tugas mapel tertentu sering sebenarnya merasa tidak mampu, bukan sekadar malas.',
      '## 3. Perubahan sikap menjelang jam mapel tertentu',
      'Anak yang tiba-tiba jadi cemas, mengeluh sakit perut, atau moody menjelang jam mapel tertentu bisa jadi sedang menghindari situasi yang membuatnya merasa gagal di depan teman-temannya.',
      '## 4. Kesulitan menjelaskan kembali apa yang dipelajari',
      'Coba minta anak menjelaskan kembali apa yang baru dipelajari di sekolah. Kesulitan menjelaskan dengan kata-kata sendiri sering jadi tanda pemahamannya masih dangkal, meski sekilas terlihat "mengikuti" pelajaran.',
      '## 5. Kehilangan minat belajar secara umum',
      'Anak yang dulunya antusias lalu berangsur-angsur kehilangan minat belajar secara umum (bukan cuma satu mapel) perlu diajak bicara lebih dalam — bisa jadi ada tekanan atau kesulitan yang belum terungkap.',
      '## Cara mendukungnya',
      'Mulai dengan komunikasi terbuka tanpa menghakimi, koordinasi dengan wali kelas atau guru mapel terkait, dan pertimbangkan bantuan tambahan (les, bimbingan belajar, atau pendampingan ekstra di rumah) sesuai kebutuhan spesifik anak — bukan disamaratakan dengan anak lain.',
    ],
  },
];

export function getArticleBySlug(slug: string): BlogArticle | undefined {
  return BLOG_ARTICLES.find((a) => a.slug === slug);
}
