export interface BlogArticle {
  slug: string;
  title: string;
  pill: string; // judul singkat untuk carousel/teaser (LembarGuruApp.tsx)
  excerpt: string;
  category: string;
  date: string; // ISO
  content: string[]; // paragraf/heading, dirender apa adanya per baris
}

export const BLOG_ARTICLES: BlogArticle[] = [
  {
    slug: 'kiat-sukses-mendidik-generasi-sekarang',
    title: '7 Kiat Sukses Mendidik Generasi Sekarang',
    pill: 'Kiat Sukses Mendidik',
    excerpt: 'Siswa hari ini tumbuh dengan gawai di tangan dan informasi yang datang dari segala arah. Berikut pendekatan yang terbukti efektif untuk mendidik mereka tanpa kehilangan wibawa maupun koneksi.',
    category: 'Kiat Mendidik',
    date: '2026-06-02',
    content: [
      'Mendidik siswa generasi sekarang membutuhkan pendekatan yang berbeda dari satu dekade lalu. Mereka terbiasa dengan informasi instan, tapi justru karena itu mereka butuh figur guru yang bisa membimbing cara berpikir, bukan sekadar menyampaikan materi.',
      '## 1. Bangun hubungan sebelum menuntut hasil',
      'Siswa yang merasa dipahami akan jauh lebih terbuka menerima arahan, termasuk kritik. Luangkan waktu di awal semester untuk mengenal minat dan latar belakang siswa, bukan langsung masuk ke materi.',
      '## 2. Jelaskan alasan di balik aturan',
      'Generasi sekarang jarang patuh hanya karena "kata guru". Mereka lebih kooperatif kalau paham kenapa sebuah aturan atau tugas itu penting untuk mereka, bukan cuma untuk memenuhi kurikulum.',
      '## 3. Beri ruang untuk salah',
      'Rasa takut salah sering membuat siswa diam di kelas. Ciptakan suasana di mana kesalahan adalah bagian normal dari belajar, bukan sesuatu yang memalukan.',
      '## 4. Manfaatkan teknologi, jangan melawannya',
      'Daripada melarang gawai sepenuhnya, arahkan penggunaannya untuk hal produktif: riset cepat, kuis interaktif, atau kolaborasi tugas kelompok.',
      '## 5. Konsisten, bukan keras',
      'Ketegasan yang konsisten jauh lebih efektif daripada sesekali marah besar. Siswa belajar dari pola, bukan dari ledakan emosi sesaat.',
      '## 6. Rayakan progres kecil',
      'Tidak semua siswa akan langsung menonjol. Mengapresiasi kemajuan kecil membangun motivasi jangka panjang yang jauh lebih tahan lama dibanding tekanan nilai semata.',
      '## 7. Jaga diri sendiri',
      'Guru yang kelelahan sulit memberi yang terbaik. Kelola waktu dan energi supaya bisa hadir penuh untuk siswa, bukan sekadar menyelesaikan jam mengajar.',
    ],
  },
  {
    slug: 'cara-mengajar-efektif-di-kelas-besar',
    title: 'Cara Mengajar Efektif di Kelas dengan Jumlah Siswa Besar',
    pill: 'Cara Mengajar Efektif',
    excerpt: 'Mengelola 30-40 siswa sekaligus bukan perkara mudah. Berikut strategi praktis supaya pembelajaran tetap efektif meski kelas penuh sesak.',
    category: 'Cara Mengajar',
    date: '2026-06-10',
    content: [
      'Kelas dengan jumlah siswa besar sering membuat interaksi personal terasa mustahil. Padahal dengan strategi yang tepat, keterbatasan ini bisa disiasati tanpa mengorbankan kualitas pembelajaran.',
      '## Bagi kelas jadi kelompok kecil',
      'Diskusi dalam kelompok 4-5 orang jauh lebih efektif daripada diskusi satu kelas penuh. Setiap siswa punya kesempatan lebih besar untuk bicara dan terlibat aktif.',
      '## Gunakan sistem giliran yang jelas',
      'Alih-alih menunjuk siswa secara acak (yang sering hanya mengenai segelintir siswa aktif), buat sistem giliran tersistematis supaya semua siswa mendapat kesempatan yang sama untuk merespons.',
      '## Manfaatkan penilaian sebaya (peer assessment)',
      'Melibatkan siswa untuk saling menilai tugas sederhana (dengan rubrik yang jelas) meringankan beban koreksi guru sekaligus melatih siswa berpikir kritis.',
      '## Siapkan instruksi tertulis, bukan hanya lisan',
      'Di kelas besar, instruksi lisan mudah tidak terdengar oleh siswa di baris belakang. Tuliskan instruksi utama di papan tulis atau bagikan lembar kerja agar semua siswa punya rujukan yang sama.',
      '## Manfaatkan "zona kerja" di kelas',
      'Atur area tertentu untuk kerja mandiri, area lain untuk diskusi kelompok. Pengaturan fisik ini membantu mengelola kebisingan dan fokus tanpa harus terus-menerus menegur.',
    ],
  },
  {
    slug: 'menghadapi-berbagai-sifat-siswa-di-kelas',
    title: 'Cara Menghadapi Berbagai Sifat Siswa di Kelas',
    pill: 'Menghadapi Sifat Siswa',
    excerpt: 'Dari siswa pendiam hingga yang paling ramai, setiap karakter butuh pendekatan berbeda. Kenali pola umum dan cara meresponsnya secara efektif.',
    category: 'Manajemen Kelas',
    date: '2026-06-18',
    content: [
      'Satu kelas biasanya berisi siswa dengan karakter yang sangat beragam. Memaksakan satu pendekatan untuk semua justru sering memperbesar masalah, bukan menyelesaikannya.',
      '## Siswa pendiam',
      'Jangan buru-buru menganggap siswa pendiam sebagai tidak paham atau tidak peduli. Beri ruang untuk merespons lewat tulisan atau diskusi kelompok kecil, sebelum diminta bicara di depan kelas.',
      '## Siswa yang mendominasi diskusi',
      'Apresiasi antusiasmenya, tapi tetapkan aturan giliran bicara yang jelas supaya siswa lain juga dapat kesempatan. Bisa juga diberi peran khusus, misalnya sebagai moderator kelompok.',
      '## Siswa yang mudah bosan dan mengganggu',
      'Sering kali ini sinyal bahwa materi terlalu mudah atau metode penyampaian kurang variatif. Coba selingi dengan aktivitas yang lebih menantang atau berbasis gerak.',
      '## Siswa yang cemas berlebihan pada ujian',
      'Bantu dengan memecah target besar jadi target kecil yang lebih mudah dicapai, dan berikan umpan balik yang menekankan proses, bukan hanya nilai akhir.',
      '## Siswa yang sering menantang otoritas guru',
      'Hindari konfrontasi di depan kelas yang bisa memperbesar ego kedua belah pihak. Ajak bicara empat mata, dengarkan alasan di baliknya, baru tetapkan batasan yang jelas.',
      '## Kuncinya: observasi sebelum bereaksi',
      'Sebelum menegur atau mengambil tindakan, coba pahami dulu pola perilaku dan kemungkinan penyebabnya. Respons yang tepat sasaran jauh lebih efektif daripada respons yang cepat tapi asal.',
    ],
  },
  {
    slug: 'menyusun-rpp-yang-benar-benar-terpakai',
    title: 'Menyusun RPP yang Benar-Benar Terpakai, Bukan Sekadar Administrasi',
    pill: 'Menyusun RPP Efektif',
    excerpt: 'RPP sering jadi beban administratif yang dibuat asal jadi. Padahal RPP yang baik justru mempermudah guru saat mengajar. Ini caranya.',
    category: 'Cara Mengajar',
    date: '2026-06-24',
    content: [
      'Banyak guru menyusun RPP hanya untuk memenuhi kewajiban administratif, lalu tidak pernah membukanya lagi saat mengajar. Padahal RPP yang disusun dengan baik seharusnya jadi alat bantu nyata di kelas.',
      '## Mulai dari tujuan, bukan dari kegiatan',
      'Tentukan dulu apa yang harus bisa dilakukan siswa di akhir pembelajaran, baru rancang kegiatan yang benar-benar mengarah ke sana — bukan sebaliknya.',
      '## Buat singkat dan mudah dibaca sekilas',
      'RPP yang terlalu panjang justru jarang dibuka lagi saat mengajar. Format ringkas dengan poin-poin kunci jauh lebih praktis dipakai di tengah kesibukan kelas.',
      '## Sertakan rencana cadangan',
      'Materi tidak selalu berjalan sesuai rencana. Siapkan alternatif kegiatan singkat untuk kondisi kelas yang lebih cepat atau lebih lambat dari perkiraan.',
      '## Sesuaikan dengan kondisi kelas, bukan kelas ideal',
      'RPP yang disalin mentah dari contoh sering tidak cocok dengan kondisi siswa sesungguhnya. Sesuaikan tingkat kesulitan dan durasi dengan karakteristik kelas yang benar-benar dihadapi.',
    ],
  },
  {
    slug: 'membangun-motivasi-belajar-siswa',
    title: 'Membangun Motivasi Belajar Siswa yang Tahan Lama',
    pill: 'Membangun Motivasi Belajar',
    excerpt: 'Motivasi yang dibangun dari rasa takut nilai jelek cenderung cepat pudar. Berikut cara menumbuhkan motivasi belajar yang lebih tahan lama.',
    category: 'Kiat Mendidik',
    date: '2026-07-01',
    content: [
      'Motivasi belajar yang hanya bersumber dari rasa takut (takut nilai jelek, takut dimarahi) cenderung hilang begitu tekanan itu tidak ada lagi. Motivasi yang lebih tahan lama biasanya tumbuh dari rasa relevan dan rasa mampu.',
      '## Kaitkan materi dengan kehidupan nyata siswa',
      'Siswa lebih termotivasi belajar sesuatu yang terasa relevan dengan hidup mereka. Tunjukkan contoh konkret bagaimana materi dipakai di luar kelas.',
      '## Beri tantangan yang pas, jangan terlalu mudah atau sulit',
      'Tugas yang terlalu mudah terasa membosankan; yang terlalu sulit membuat siswa menyerah lebih dulu. Cari titik tengah yang membuat siswa merasa tertantang tapi tetap yakin bisa berhasil.',
      '## Berikan umpan balik spesifik, bukan sekadar angka',
      'Nilai angka saja tidak memberi tahu siswa apa yang harus diperbaiki. Umpan balik yang spesifik membantu mereka melihat jalan untuk berkembang.',
      '## Libatkan siswa dalam menentukan target belajarnya',
      'Siswa yang ikut menentukan targetnya sendiri (bukan cuma menerima target dari guru) cenderung merasa lebih bertanggung jawab untuk mencapainya.',
    ],
  },
  {
    slug: 'trik-belajar-cepat-dan-efektif',
    title: '7 Trik Belajar Cepat dan Efektif yang Terbukti Ilmiah',
    pill: 'Trik Belajar Cepat',
    excerpt: 'Belajar lama bukan berarti belajar efektif. Berikut teknik belajar yang didukung riset dan bisa langsung dicoba siswa mulai hari ini.',
    category: 'Tips Belajar Siswa',
    date: '2026-07-03',
    content: [
      'Banyak siswa menghabiskan berjam-jam membaca ulang catatan tapi tetap lupa saat ujian. Masalahnya bukan kurang waktu belajar, tapi caranya yang kurang efektif. Berikut beberapa teknik yang terbukti lebih hasil-guna dibanding sekadar membaca berulang.',
      '## 1. Active recall, bukan membaca ulang',
      'Daripada membaca ulang materi, coba tutup buku dan tulis kembali apa yang masih diingat. Proses mengingat aktif ini jauh lebih efektif memperkuat memori dibanding membaca pasif berkali-kali.',
      '## 2. Spaced repetition',
      'Ulangi materi dengan jeda waktu yang makin panjang (misalnya hari ini, besok, tiga hari lagi, seminggu lagi) alih-alih belajar maraton semalam sebelum ujian. Otak lebih kuat menyimpan informasi yang diulang secara berkala.',
      '## 3. Teknik Feynman: ajarkan ke orang lain',
      'Coba jelaskan materi dengan bahasa sederhana seolah-olah mengajari adik kelas. Bagian yang terasa sulit dijelaskan biasanya adalah bagian yang sebenarnya belum benar-benar dipahami.',
      '## 4. Pomodoro: fokus dalam blok pendek',
      'Belajar 25 menit penuh fokus, istirahat 5 menit, ulangi. Blok waktu pendek dengan jeda membantu menjaga konsentrasi dibanding belajar berjam-jam tanpa henti yang justru menurunkan fokus.',
      '## 5. Kaitkan materi baru dengan yang sudah dipahami',
      'Informasi baru lebih mudah menempel kalau dikaitkan dengan sesuatu yang sudah diketahui. Cari analogi atau contoh dari kehidupan sehari-hari untuk konsep yang terasa abstrak.',
      '## 6. Variasikan tempat dan cara belajar',
      'Belajar di tempat yang sama dengan cara yang sama terus-menerus membuat memori terlalu bergantung pada konteks itu. Sesekali ganti suasana atau format belajar (menulis, diagram, rekaman suara) supaya ingatan lebih fleksibel.',
      '## 7. Cukup tidur, jangan begadang',
      'Konsolidasi memori terjadi saat tidur. Belajar maraton semalaman sambil mengorbankan jam tidur justru membuat otak lebih sulit menyimpan apa yang baru dipelajari.',
    ],
  },
  {
    slug: 'cara-mengatur-waktu-belajar-siswa',
    title: 'Cara Mengatur Waktu Belajar Supaya Tidak Keteteran Menjelang Ujian',
    pill: 'Mengatur Waktu Belajar',
    excerpt: 'Menumpuk semua materi di malam terakhir sebelum ujian nyaris selalu berujung stres. Berikut cara mengatur waktu belajar yang lebih realistis.',
    category: 'Tips Belajar Siswa',
    date: '2026-07-04',
    content: [
      'Banyak siswa baru mulai belajar serius beberapa hari sebelum ujian, lalu kewalahan karena materi menumpuk. Mengatur waktu belajar sejak awal jauh lebih ringan daripada mengejar ketertinggalan di menit-menit akhir.',
      '## Buat jadwal mingguan, bukan cuma harian',
      'Lihat gambaran besar dulu: mapel apa saja yang perlu dipelajari minggu ini, dan berapa banyak waktu yang realistis bisa dialokasikan. Baru pecah jadi jadwal harian yang lebih detail.',
      '## Dahulukan materi yang paling sulit',
      'Kerjakan materi yang paling menantang saat energi dan fokus masih tinggi (biasanya di awal sesi belajar), bukan ditunda ke akhir saat sudah lelah.',
      '## Sisihkan waktu untuk mengulang, bukan cuma materi baru',
      'Jadwal yang cuma diisi materi baru terus-menerus membuat materi lama terlupakan. Sisihkan sebagian waktu tiap minggu khusus untuk mengulang apa yang sudah dipelajari sebelumnya.',
      '## Pecah tugas besar jadi langkah kecil',
      'Tugas atau target belajar yang besar terasa berat kalau dilihat sekaligus. Pecah jadi langkah-langkah kecil dengan tenggat masing-masing supaya progresnya terasa dan tidak menumpuk di akhir.',
      '## Beri jeda istirahat yang sesungguhnya',
      'Istirahat sambil scroll media sosial sering tidak benar-benar memulihkan energi. Coba istirahat dengan aktivitas yang benar-benar melepaskan pikiran dari layar, seperti jalan kaki singkat atau meregangkan badan.',
    ],
  },
  {
    slug: 'tips-menjadi-guru-pemula-percaya-diri',
    title: 'Tips Menjadi Guru Pemula yang Percaya Diri di Depan Kelas',
    pill: 'Tips Menjadi Guru',
    excerpt: 'Hari pertama mengajar sering terasa menegangkan, bahkan untuk yang sudah siap secara materi. Berikut cara membangun rasa percaya diri di depan kelas.',
    category: 'Tips Menjadi Guru',
    date: '2026-07-06',
    content: [
      'Rasa grogi di hari-hari pertama mengajar itu wajar, bahkan dialami hampir semua guru berpengalaman waktu masih pemula. Yang membedakan bukan tidak pernah gugup, tapi tahu cara mengelolanya supaya tidak mengganggu performa di kelas.',
      '## Kuasai 10 menit pertama',
      'Kesan awal di 10 menit pertama sering menentukan suasana sepanjang jam pelajaran. Siapkan pembuka yang jelas dan terlatih — tidak perlu rumit, cukup yang membuat guru terlihat tenang dan siap.',
      '## Wibawa dibangun dari konsistensi, bukan suara keras',
      'Siswa lebih menghormati guru yang konsisten dengan aturan dan janjinya, bukan yang paling galak. Tetapkan batasan yang jelas sejak awal dan jalankan secara konsisten.',
      '## Wajar tidak tahu semua jawaban',
      'Guru pemula sering takut terlihat tidak kompeten kalau tidak bisa jawab pertanyaan siswa. Padahal jujur mengatakan "saya cek dulu, nanti saya jawab" jauh lebih membangun kepercayaan daripada berpura-pura tahu.',
      '## Siapkan rencana cadangan',
      'Rasa percaya diri sering runtuh saat rencana mengajar tidak berjalan sesuai perkiraan. Siapkan alternatif kegiatan singkat untuk kondisi kelas yang lebih cepat atau lebih lambat dari perkiraan, supaya tidak panik di tengah jalan.',
      '## Belajar dari guru senior, tapi temukan gaya sendiri',
      'Amati cara mengajar guru yang lebih berpengalaman, tapi jangan memaksakan gaya yang tidak sesuai dengan kepribadian sendiri. Siswa bisa merasakan kalau seorang guru tidak nyaman dengan caranya sendiri.',
      '## Refleksi setelah tiap kelas, jangan cuma menilai diri sendiri',
      'Setelah mengajar, catat apa yang berjalan baik dan apa yang perlu diperbaiki — bukan untuk menghakimi diri sendiri, tapi supaya ada progres nyata dari waktu ke waktu.',
    ],
  },
  {
    slug: 'mengembangkan-karier-sebagai-guru',
    title: 'Cara Mengembangkan Karier sebagai Guru di Luar Mengajar di Kelas',
    pill: 'Mengembangkan Karier Guru',
    excerpt: 'Profesi guru punya banyak jalur pengembangan di luar rutinitas mengajar harian. Berikut beberapa arah yang bisa mulai dijajaki.',
    category: 'Tips Menjadi Guru',
    date: '2026-07-07',
    content: [
      'Banyak guru merasa kariernya "mentok" begitu-begitu saja setiap tahun. Padahal profesi guru punya banyak jalur pengembangan yang jarang disadari, di luar sekadar naik jam mengajar atau menunggu jadi kepala sekolah.',
      '## Ikut komunitas dan pelatihan guru',
      'Komunitas guru (daring maupun luring) jadi tempat bertukar metode mengajar, materi, dan dukungan moral. Banyak juga pelatihan gratis atau bersubsidi yang bisa memperkaya kompetensi tanpa biaya besar.',
      '## Kembangkan kompetensi digital',
      'Guru yang terbiasa memakai alat bantu digital untuk menyusun materi, soal, dan penilaian punya nilai tambah signifikan, terutama di sekolah yang terus mendorong transformasi digital.',
      '## Jadi penulis modul atau materi ajar',
      'Pengalaman mengajar bertahun-tahun adalah modal berharga untuk menulis modul, buku ajar, atau konten edukasi. Ini bisa jadi jalur penghasilan tambahan sekaligus memperluas dampak di luar kelas sendiri.',
      '## Ikut lomba inovasi pembelajaran',
      'Banyak kompetisi karya inovasi pembelajaran tingkat sekolah, daerah, hingga nasional. Selain pengakuan, proses menyusun karya inovasi juga mendorong guru terus bereksperimen dengan metode baru.',
      '## Jajaki peran mentor atau pembina guru baru',
      'Mendampingi guru yang lebih baru tidak cuma membantu mereka, tapi juga melatih kemampuan kepemimpinan yang berguna kalau suatu saat ingin mengambil peran struktural.',
    ],
  },
  {
    slug: 'panduan-orang-tua-mendampingi-anak-belajar',
    title: 'Panduan Orang Tua Mendampingi Anak Belajar di Rumah Tanpa Drama',
    pill: 'Panduan Orang Tua',
    excerpt: 'Mendampingi anak belajar di rumah sering berujung emosi naik, baik dari orang tua maupun anak. Berikut cara mendampingi yang lebih tenang dan efektif.',
    category: 'Panduan Orang Tua',
    date: '2026-07-08',
    content: [
      'Niat baik mendampingi anak belajar di rumah sering berubah jadi pertengkaran kecil karena cara pendekatannya kurang tepat. Berikut beberapa cara mendampingi yang lebih tenang, tanpa mengorbankan hubungan dengan anak.',
      '## Buat rutinitas, bukan cuma aturan dadakan',
      'Anak lebih mudah menerima waktu belajar yang sudah jadi rutinitas harian dibanding perintah mendadak "ayo belajar sekarang". Sepakati bersama jam belajar yang konsisten setiap hari.',
      '## Dampingi, jangan mengambil alih',
      'Godaan untuk langsung membetulkan atau mengerjakan tugas anak itu besar, apalagi kalau melihat anak kesulitan. Tapi anak belajar justru dari proses mencoba dan salah — peran orang tua lebih ke mengarahkan, bukan menggantikan.',
      '## Jangan cuma fokus ke nilai akhir',
      'Terlalu menekankan nilai membuat anak takut salah dan menghindari tantangan. Apresiasi juga usaha dan proses belajarnya, bukan cuma angka di rapor.',
      '## Kelola emosi diri sendiri dulu',
      'Rasa frustrasi orang tua sering lebih cepat meningkat daripada anaknya sendiri. Kalau mulai emosi, lebih baik jeda sebentar daripada melanjutkan sesi belajar dalam suasana tegang.',
      '## Komunikasi rutin dengan guru di sekolah',
      'Guru punya gambaran perkembangan anak dari sisi yang mungkin tidak terlihat di rumah. Komunikasi rutin membantu orang tua memberi dukungan yang lebih tepat sasaran, bukan menerka-nerka sendiri.',
    ],
  },
  {
    slug: 'tanda-anak-butuh-bantuan-belajar-tambahan',
    title: '5 Tanda Anak Butuh Bantuan Belajar Tambahan dan Cara Mendukungnya',
    pill: 'Tanda Anak Butuh Bantuan',
    excerpt: 'Tidak semua anak akan bicara terus terang kalau kesulitan mengikuti pelajaran. Kenali tanda-tandanya sebelum semakin tertinggal.',
    category: 'Panduan Orang Tua',
    date: '2026-07-09',
    content: [
      'Anak tidak selalu bisa mengungkapkan dengan jelas kalau sedang kesulitan mengikuti pelajaran di sekolah. Mengenali tanda-tandanya lebih awal membantu orang tua memberi dukungan sebelum masalahnya makin menumpuk.',
      '## 1. Nilai menurun bertahap, bukan tiba-tiba',
      'Penurunan nilai yang bertahap di satu mapel tertentu sering jadi sinyal awal ada konsep dasar yang belum benar-benar dipahami, bukan sekadar kurang belajar semalam sebelum ujian.',
      '## 2. Menghindari tugas mapel tertentu',
      'Anak yang selalu menunda atau mencari alasan untuk tidak mengerjakan tugas mapel tertentu sering sebenarnya merasa tidak mampu, bukan sekadar malas.',
      '## 3. Perubahan sikap menjelang jam mapel tertentu',
      'Anak yang tiba-tiba jadi cemas, mengeluh sakit perut, atau moody menjelang jam mapel tertentu bisa jadi sedang menghindari situasi yang membuatnya merasa gagal di depan teman-temannya.',
      '## 4. Kesulitan menjelaskan kembali apa yang dipelajari',
      'Coba minta anak menjelaskan kembali apa yang baru dipelajari di sekolah. Kesulitan menjelaskan dengan kata-kata sendiri sering jadi tanda pemahamannya masih dangkal, meski sekilas terlihat "mengikuti" pelajaran.',
      '## 5. Kehilangan minat belajar secara umum',
      'Anak yang dulunya antusias lalu berangsur-angsur kehilangan minat belajar secara umum (bukan cuma satu mapel) perlu diajak bicara lebih dalam — bisa jadi ada tekanan atau kesulitan yang belum terungkap.',
      '## Cara mendukungnya',
      'Mulai dengan komunikasi terbuka tanpa menghakimi, koordinasi dengan wali kelas atau guru mapel terkait, dan pertimbangkan bantuan tambahan (les, bimbingan belajar, atau pendampingan ekstra di rumah) sesuai kebutuhan spesifik anak — bukan disamaratakan dengan anak lain.',
    ],
  },
  {
    slug: 'manfaat-alat-bantu-guru-lembarguru',
    title: 'Manfaat 18 Alat Bantu Guru: Rutinitas Harian yang Lebih Ringan Tanpa Kurangi Kualitas Mengajar',
    pill: 'Manfaat Alat Bantu Guru',
    excerpt: 'Di luar generator soal utama, LembarGuru punya 18 tool ringan untuk hal-hal yang tiap hari dikerjakan guru — dari menyusun RPP sampai memantau nilai. Berikut manfaatnya per kelompok kebutuhan.',
    category: 'Produktivitas Guru',
    date: '2026-07-10',
    content: [
      'Banyak pekerjaan guru sebetulnya bukan soal mengajar di depan kelas, melainkan hal-hal administratif dan persiapan yang memakan waktu di luar jam mengajar: menyusun RPP, membuat rubrik penilaian, merekap nilai, sampai menyiapkan energizer supaya kelas tidak lesu. "Alat Bantu Guru" di LembarGuru dibuat untuk memangkas waktu di bagian-bagian itu, supaya energi guru bisa lebih banyak dicurahkan ke hal yang benar-benar butuh sentuhan manusia: mendampingi siswa.',
      '## Hemat waktu di tahap persiapan mengajar',
      'Generator RPP menyusun RPP/modul ajar otomatis sesuai kurikulum yang dipakai, Silabus & KI/KD membantu memetakan kompetensi inti dan dasar tanpa mengetik ulang dari nol, dan Rubrik Penilaian menyusun kriteria penilaian tugas/proyek dalam hitungan detik. Ketiganya menyasar dokumen administratif yang sering jadi beban di awal semester — bukan menggantikan penilaian profesional guru, tapi menghilangkan bagian paling melelahkan: mulai dari halaman kosong.',
      '## Kelola kelas jadi lebih rapi, bukan lebih ribet',
      'Presensi Digital merekam absensi harian langsung di perangkat yang dipakai, Jadwal Mengajar membantu memantau jadwal dan pengingat mengajar, Bagi Kelompok membagi siswa ke kelompok secara otomatis dan adil, Acak Nama Siswa memilih nama secara acak untuk sesi tanya-jawab supaya semua siswa kebagian giliran, dan Timer Kelas mengatur waktu untuk aktivitas atau ujian di kelas. Tool-tool ini kecil satu-satu, tapi kalau dipakai rutin, mengurangi banyak "pekerjaan remeh" yang sebetulnya menyita perhatian di tengah jam mengajar.',
      '## Bikin suasana kelas lebih hidup',
      'Papan Poin Kelas menyediakan papan skor gamifikasi untuk memotivasi siswa berpartisipasi, Ice Breaker memberi ide game dan energizer singkat saat kelas mulai lesu, Flashcard membuat kartu belajar interaktif untuk hafalan, dan Baca Teks (TTS) mengubah teks atau cerita jadi audio — berguna untuk variasi metode belajar atau membantu siswa dengan kebutuhan belajar berbeda. Kelas yang hidup bukan soal guru harus selalu "tampil", tapi soal punya alat bantu yang siap dipakai kapan pun suasana perlu diubah.',
      '## Pantau nilai dan perkembangan siswa tanpa Excel manual',
      'Kalkulator Nilai menghitung rata-rata nilai berbobot dan status ketuntasan (KKM) otomatis, Konversi Nilai mengubah skor jadi skala nilai/huruf sesuai standar yang dipakai, Catatan Siswa mencatat perkembangan dan perilaku tiap siswa secara individual, dan Analisis Soal mengevaluasi tingkat kesulitan serta validitas soal yang sudah dipakai. Dikombinasikan, tool-tool ini menggantikan kebiasaan lama mencatat semuanya manual di kertas atau spreadsheet terpisah-pisah.',
      '## Simpan dan apresiasi hasil kerja siswa',
      'Bank Soal menyimpan dan mengelola koleksi soal supaya tidak perlu menyusun ulang dari awal tiap semester, sementara Sertifikat membuat sertifikat atau piagam penghargaan untuk siswa berprestasi maupun sekadar apresiasi partisipasi. Dua tool ini melengkapi siklus: soal yang sudah dipakai tersimpan rapi untuk dipakai lagi, dan hasil belajar siswa mendapat pengakuan yang layak.',
      '## Semuanya gratis dan tidak menambah beban belajar baru',
      'Ke-18 tool ini sengaja dibuat ringan — tanpa perlu login untuk sebagian besar, tanpa alur rumit, dan bisa langsung dipakai dari toolbar "Alat Bantu Guru" di halaman utama LembarGuru. Filosofinya sama dengan generator soal utama: simple seperti Google, bukan aplikasi baru yang harus dipelajari dulu sebelum bisa dipakai.',
    ],
  },
  {
    slug: 'tool-generator-rpp',
    title: 'Generator RPP — Berhenti Mulai dari Halaman Kosong Lagi',
    pill: 'Generator RPP',
    excerpt: 'Susun RPP/modul ajar otomatis sesuai kurikulum yang dipakai — bukan pengganti keputusan guru, tapi penghilang bagian paling melelahkan: mulai dari halaman kosong.',
    category: 'Alat Bantu Guru',
    date: '2026-07-11',
    content: [
      'Generator RPP menyusun rancangan pelaksanaan pembelajaran (atau modul ajar untuk Kurikulum Merdeka) secara otomatis berdasarkan mapel, kelas, dan topik yang dipilih.',
      '## Manfaatnya',
      'RPP sering jadi beban administratif yang dikerjakan terburu-buru menjelang deadline, padahal seharusnya jadi alat bantu nyata saat mengajar. Generator RPP memberi kerangka lengkap (tujuan pembelajaran, kegiatan, penilaian) dalam hitungan detik, sehingga waktu guru bisa dialihkan ke menyesuaikan isinya dengan kondisi kelas, bukan menyusun dari nol.',
      '## Kapan Sebaiknya Dipakai',
      'Paling terasa manfaatnya di awal semester saat harus menyusun banyak RPP sekaligus, saat topik/bab berganti di tengah semester, atau saat butuh RPP mendadak untuk keperluan supervisi/akreditasi.',
      '## Cara Memakainya Secara Efektif',
      'Isi kurikulum, kelas, dan topik seakurat mungkin supaya kerangka yang dihasilkan relevan. Jangan langsung dipakai mentah — sesuaikan kegiatan dan alokasi waktu dengan karakteristik kelas yang sebenarnya dihadapi, karena generator tidak tahu kondisi riil siswa di kelas tersebut.',
      '## Contoh & Kondisi Penggunaan',
      'Seorang guru IPA kelas 7 baru tahu malam ini bahwa besok pagi harus mengajar topik ekosistem karena RPP lama tidak relevan lagi dengan revisi kurikulum sekolah. Generator RPP memberi kerangka awal yang tinggal disesuaikan, jauh lebih cepat dibanding menyusun dari halaman kosong pada jam larut malam.',
    ],
  },
  {
    slug: 'tool-bank-soal',
    title: 'Bank Soal — Ambil Soal Tambahan Tanpa Generate Ulang dari Nol',
    pill: 'Bank Soal',
    excerpt: 'Kolam soal bersama dari hasil generate semua guru pengguna LembarGuru — cara cepat dapat soal tambahan tanpa generate ulang dari nol.',
    category: 'Alat Bantu Guru',
    date: '2026-07-12',
    content: [
      'Bank Soal menyimpan dan menampilkan kumpulan soal dari hasil generate seluruh pengguna LembarGuru, bisa difilter berdasarkan mata pelajaran dan kelas.',
      '## Manfaatnya',
      'Tidak semua kebutuhan soal harus di-generate ulang dari awal — Bank Soal jadi sumber cadangan yang bisa langsung dipakai atau dijadikan referensi, terutama saat butuh soal dengan cepat atau ingin variasi dari gaya soal sendiri.',
      '## Kapan Sebaiknya Dipakai',
      'Cocok dipakai saat butuh soal tambahan mendadak (misalnya untuk remedial atau pengayaan), saat mencari inspirasi variasi soal untuk topik yang sama, atau saat ingin menyiapkan cadangan soal ulangan tanpa harus generate baru tiap kali.',
      '## Cara Memakainya Secara Efektif',
      'Gunakan filter mapel dan kelas supaya hasil yang muncul relevan, dan selalu baca ulang soal yang diambil sebelum dipakai — karena berasal dari kolam bersama, kualitas dan gaya penulisannya bisa bervariasi antar soal.',
      '## Contoh & Kondisi Penggunaan',
      'Guru Matematika kelas 8 butuh 10 soal tambahan untuk sesi remedial siang ini. Daripada generate baru dan menunggu, ia mengambil soal-soal yang relevan langsung dari Bank Soal, lalu menyesuaikan sedikit redaksinya dengan gaya mengajarnya sendiri.',
    ],
  },
  {
    slug: 'tool-analisis-soal',
    title: 'Analisis Soal — Cek Soal Mana yang Perlu Diperbaiki Sebelum Diujikan',
    pill: 'Analisis Soal',
    excerpt: 'Evaluasi tingkat kesulitan dan validitas soal yang sudah dipakai, supaya bank soal pribadi guru makin baik dari waktu ke waktu.',
    category: 'Alat Bantu Guru',
    date: '2026-07-13',
    content: [
      'Analisis Soal membantu mengevaluasi kualitas soal — apakah tingkat kesulitannya sesuai, dan apakah soal tersebut valid mengukur apa yang seharusnya diukur.',
      '## Manfaatnya',
      'Soal yang tidak pernah dievaluasi cenderung dipakai berulang tanpa perbaikan, padahal ada soal yang ternyata ambigu atau terlalu mudah/sulit. Analisis Soal memberi gambaran objektif supaya guru bisa memutuskan soal mana yang layak dipakai lagi dan mana yang perlu direvisi.',
      '## Kapan Sebaiknya Dipakai',
      'Paling berguna setelah ulangan selesai dan hasilnya sudah terlihat — terutama kalau ada soal yang banyak dijawab salah oleh siswa yang secara umum memahami materi, atau sebelum soal lama dipakai ulang di kelas paralel.',
      '## Cara Memakainya Secara Efektif',
      'Masukkan soal beserta konteksnya (materi, tingkat kelas) supaya analisisnya relevan, lalu gunakan hasilnya untuk memutuskan: revisi redaksi soal, ganti tingkat kesulitan, atau simpan sebagai soal yang sudah teruji baik.',
      '## Contoh & Kondisi Penggunaan',
      'Setelah ulangan harian, guru menyadari satu soal pilihan ganda dijawab salah oleh hampir seluruh kelas — termasuk siswa yang biasanya menguasai materi. Analisis Soal membantu menentukan apakah penyebabnya soal yang ambigu atau materi yang memang belum tersampaikan dengan baik.',
    ],
  },
  {
    slug: 'tool-silabus-ki-kd',
    title: 'Silabus & KI/KD — Beres Sekali Klik, Bukan Sepanjang Libur Awal Tahun',
    pill: 'Silabus & KI/KD',
    excerpt: 'Susun silabus dan pemetaan Kompetensi Inti/Kompetensi Dasar otomatis — dokumen administratif yang paling sering jadi beban awal tahun ajaran.',
    category: 'Alat Bantu Guru',
    date: '2026-07-14',
    content: [
      'Silabus & KI/KD menyusun kerangka silabus lengkap dengan pemetaan Kompetensi Inti dan Kompetensi Dasar sesuai mapel, kelas, dan kurikulum yang dipilih.',
      '## Manfaatnya',
      'Menyusun silabus dan memetakan KI/KD secara manual memakan waktu berjam-jam, apalagi kalau harus dilakukan untuk beberapa mapel atau kelas sekaligus. Tool ini memberi kerangka dasar yang sudah terstruktur, jadi guru tinggal menyesuaikan detail sesuai kondisi sekolah.',
      '## Kapan Sebaiknya Dipakai',
      'Paling relevan di awal tahun ajaran atau semester baru, saat sekolah berganti kurikulum, atau saat guru pindah tugas ke sekolah/jenjang baru dan harus menyusun dokumen dari awal.',
      '## Cara Memakainya Secara Efektif',
      'Sesuaikan hasilnya dengan kurikulum resmi yang berlaku di sekolah masing-masing, dan lakukan pengecekan silang dengan pedoman KI/KD terbaru dari Kemendikbud — jangan disalin mentah tanpa verifikasi, terutama untuk keperluan akreditasi.',
      '## Contoh & Kondisi Penggunaan',
      'Seorang guru baru pindah ke sekolah dengan kurikulum berbeda dari sekolah sebelumnya, dan harus menyerahkan silabus lengkap sebelum tahun ajaran dimulai minggu depan. Tool ini memberi titik awal yang jauh lebih cepat dibanding menyusun dari dokumen kosong.',
    ],
  },
  {
    slug: 'tool-flashcard',
    title: 'Flashcard — Bikin Hafalan Nempel Lebih Lama Lewat Kartu Interaktif',
    pill: 'Flashcard',
    excerpt: 'Kartu belajar interaktif untuk hafalan — cocok dipadukan dengan teknik spaced repetition supaya materi lebih lama diingat.',
    category: 'Alat Bantu Guru',
    date: '2026-07-15',
    content: [
      'Flashcard membuat kartu belajar interaktif (istilah/pertanyaan di satu sisi, jawaban di sisi lain) yang bisa dipakai untuk drilling hafalan di kelas maupun mandiri.',
      '## Manfaatnya',
      'Format tanya-jawab singkat pada flashcard cocok untuk materi yang memang butuh dihafal — kosakata, rumus, istilah — dan lebih menarik perhatian siswa dibanding daftar catatan biasa.',
      '## Kapan Sebaiknya Dipakai',
      'Berguna untuk sesi mengulang kosakata atau istilah baru, drilling rumus sebelum ujian, atau sebagai aktivitas pemanasan singkat di awal kelas untuk mengaktifkan ingatan siswa dari pertemuan sebelumnya.',
      '## Cara Memakainya Secara Efektif',
      'Jangan dipakai sekali lalu ditinggalkan — kombinasikan dengan pengulangan berkala (spaced repetition) supaya materi benar-benar tersimpan di memori jangka panjang, bukan cuma hafalan semalam yang cepat hilang.',
      '## Contoh & Kondisi Penggunaan',
      'Guru Bahasa Inggris memperkenalkan 15 kosakata baru tiap minggu. Alih-alih hanya menulis di papan, ia membuat flashcard untuk drill cepat 5 menit di awal tiap kelas — termasuk mengulang kosakata minggu-minggu sebelumnya.',
    ],
  },
  {
    slug: 'tool-rubrik-penilaian',
    title: 'Rubrik Penilaian — Nilai Adil dan Gampang Dijelaskan ke Orang Tua',
    pill: 'Rubrik Penilaian',
    excerpt: 'Kriteria penilaian tugas/proyek yang jelas dan objektif — mengurangi bias penilaian sekaligus mempermudah guru menjelaskan nilai ke siswa dan orang tua.',
    category: 'Alat Bantu Guru',
    date: '2026-07-16',
    content: [
      'Rubrik Penilaian menyusun kriteria penilaian terstruktur untuk tugas atau proyek, lengkap dengan level pencapaian yang jelas untuk tiap kriteria.',
      '## Manfaatnya',
      'Penilaian tanpa rubrik cenderung subjektif dan sulit dijelaskan kalau ada yang mempertanyakan nilainya. Rubrik yang jelas membuat penilaian lebih konsisten antar siswa dan lebih mudah dikomunikasikan, baik ke siswa maupun orang tua.',
      '## Kapan Sebaiknya Dipakai',
      'Paling penting dipakai sebelum tugas proyek, presentasi, atau karya yang penilaiannya tidak sesederhana benar/salah — di mana ada banyak aspek kualitatif yang perlu dinilai secara adil.',
      '## Cara Memakainya Secara Efektif',
      'Bagikan rubrik ke siswa SEBELUM mereka mulai mengerjakan tugas, bukan setelah selesai — supaya siswa tahu persis apa yang diharapkan dan bisa mengarahkan usahanya sejak awal, bukan menerka-nerka standar penilaian guru.',
      '## Contoh & Kondisi Penggunaan',
      'Sebelum memulai proyek kelompok IPS tentang potensi daerah, guru membagikan rubrik penilaian yang mencakup kelengkapan data, kerja sama tim, dan kualitas presentasi — sehingga siswa tahu sejak awal aspek mana yang akan dinilai.',
    ],
  },
  {
    slug: 'tool-acak-nama-siswa',
    title: 'Acak Nama Siswa — Adil Tanpa Drama, Semua Siswa Kebagian Giliran',
    pill: 'Acak Nama Siswa',
    excerpt: 'Pemilihan siswa yang adil dan acak untuk sesi tanya jawab — semua siswa punya kesempatan yang sama, bukan cuma yang biasa aktif.',
    category: 'Alat Bantu Guru',
    date: '2026-07-17',
    content: [
      'Acak Nama Siswa memilih nama secara acak dari daftar kelas, berguna untuk menentukan giliran menjawab, presentasi, atau maju ke depan kelas.',
      '## Manfaatnya',
      'Tanpa alat bantu, guru cenderung (tanpa sadar) lebih sering menunjuk siswa yang sama — biasanya yang paling aktif atau paling terlihat. Pengacakan membuat kesempatan lebih merata dan mendorong semua siswa tetap siap, karena siapa pun bisa terpilih.',
      '## Kapan Sebaiknya Dipakai',
      'Cocok untuk sesi tanya jawab review pelajaran, menentukan urutan presentasi, atau kapan pun guru ingin melibatkan siswa secara acak tanpa kesan pilih kasih.',
      '## Cara Memakainya Secara Efektif',
      'Gunakan secara konsisten (bukan sesekali) supaya siswa terbiasa dan tidak merasa "ditarget" saat namanya keluar. Kalau perlu, keluarkan nama yang sudah kebagian giliran supaya kesempatan makin merata dalam satu sesi.',
      '## Contoh & Kondisi Penggunaan',
      'Saat review sebelum ulangan, guru ingin memastikan semua siswa siap menjawab kapan saja, bukan hanya yang biasa mengangkat tangan. Pengacakan nama membuat seluruh kelas tetap fokus karena tidak tahu siapa yang akan dipanggil berikutnya.',
    ],
  },
  {
    slug: 'tool-bagi-kelompok',
    title: 'Bagi Kelompok — Bagi Tim Merata Tanpa Drama Pilih-Pilih Teman',
    pill: 'Bagi Kelompok',
    excerpt: 'Bagi siswa ke dalam kelompok secara otomatis dan merata — hindari drama "pilih-pilih teman" yang sering bikin sebagian siswa merasa tersisih.',
    category: 'Alat Bantu Guru',
    date: '2026-07-18',
    content: [
      'Bagi Kelompok membagi daftar siswa ke dalam beberapa kelompok secara otomatis sesuai jumlah kelompok atau jumlah anggota yang diinginkan.',
      '## Manfaatnya',
      'Pembagian kelompok manual (apalagi kalau siswa yang memilih sendiri) sering membuat sebagian siswa merasa tersisih atau selalu sekelompok dengan orang yang sama. Pembagian otomatis lebih cepat dan terasa lebih adil bagi semua siswa.',
      '## Kapan Sebaiknya Dipakai',
      'Berguna untuk kerja kelompok dadakan, proyek, diskusi kelas, atau aktivitas apa pun yang butuh pembagian kelompok cepat tanpa perlu debat panjang di depan kelas.',
      '## Cara Memakainya Secara Efektif',
      'Untuk aktivitas singkat, pembagian acak polos sudah cukup. Tapi kalau tujuan aktivitasnya butuh keseimbangan (misalnya campuran siswa yang kuat dan yang masih perlu bantuan), pertimbangkan aturan tambahan sebelum membagi, bukan cuma mengandalkan acak murni.',
      '## Contoh & Kondisi Penggunaan',
      'Di tengah pelajaran, guru mendadak memutuskan untuk mengadakan diskusi kelompok tentang topik yang baru dibahas. Dengan 30 siswa di kelas, pembagian ke 6 kelompok bisa selesai dalam hitungan detik tanpa mengganggu momentum pelajaran.',
    ],
  },
  {
    slug: 'tool-jadwal-mengajar',
    title: 'Jadwal Mengajar — Satu Tempat, Tidak Ada Lagi Kelas yang Kelewat',
    pill: 'Jadwal Mengajar',
    excerpt: 'Kelola jadwal dan pengingat mengajar dalam satu tempat — penting terutama untuk guru yang mengajar banyak kelas atau di beberapa sekolah.',
    category: 'Alat Bantu Guru',
    date: '2026-07-19',
    content: [
      'Jadwal Mengajar membantu mencatat dan memantau jadwal mengajar beserta pengingatnya, supaya tidak ada kelas atau jam yang terlewat.',
      '## Manfaatnya',
      'Guru dengan banyak kelas atau jam mengajar berisiko salah kelas, salah topik, atau lupa jadwal — terutama kalau jadwalnya sering berubah. Tool ini memberi satu tempat rujukan yang jelas, mengurangi risiko itu.',
      '## Kapan Sebaiknya Dipakai',
      'Paling terasa manfaatnya untuk guru yang mengajar di banyak kelas paralel, guru honorer yang mengajar di lebih dari satu sekolah, atau siapa pun yang jadwalnya sering berubah tiap semester.',
      '## Cara Memakainya Secara Efektif',
      'Update jadwal segera setiap kali ada perubahan (bukan ditunda), dan jadikan kebiasaan mengecek jadwal di pagi hari sebelum berangkat mengajar supaya tidak ada kejutan di tengah hari.',
      '## Contoh & Kondisi Penggunaan',
      'Seorang guru honorer mengajar di tiga sekolah berbeda dengan jadwal yang berubah tiap semester. Mencatat semuanya di satu tempat membantu menghindari kesalahan datang ke sekolah yang salah atau lupa jam mengajar.',
    ],
  },
  {
    slug: 'tool-konversi-nilai',
    title: 'Konversi Nilai — Ubah Skor ke Skala Nilai Secara Instan',
    pill: 'Konversi Nilai',
    excerpt: 'Ubah skor mentah jadi skala nilai atau huruf sesuai standar sekolah — cepat dan konsisten, terutama saat rekap nilai akhir semester.',
    category: 'Alat Bantu Guru',
    date: '2026-07-20',
    content: [
      'Konversi Nilai mengubah skor angka menjadi skala nilai atau huruf (misalnya A–E) sesuai standar penilaian yang berlaku.',
      '## Manfaatnya',
      'Konversi manual untuk puluhan siswa rawan salah hitung dan memakan waktu. Tool ini membuat prosesnya cepat dan konsisten, terutama saat harus dilakukan untuk banyak siswa sekaligus menjelang tenggat rapor.',
      '## Kapan Sebaiknya Dipakai',
      'Paling relevan saat rekap nilai akhir semester, menyusun laporan ke orang tua, atau kapan pun skor mentah perlu diterjemahkan ke format yang dipakai dalam dokumen resmi sekolah.',
      '## Cara Memakainya Secara Efektif',
      'Pastikan skala konversi yang dipakai sudah sesuai standar sekolah sebelum menjalankan konversi massal — kesalahan skala di awal akan terbawa ke semua nilai yang dikonversi setelahnya.',
      '## Contoh & Kondisi Penggunaan',
      'Menjelang pembagian rapor, guru punya rekap nilai mentah 0–100 untuk 32 siswa yang perlu diubah ke skala huruf sesuai format rapor sekolah. Konversi otomatis menghindarkan kesalahan hitung manual yang biasa terjadi saat terburu-buru.',
    ],
  },
  {
    slug: 'tool-timer-kelas',
    title: 'Timer Kelas — Bantu Siswa Kelola Waktu Sendiri di Kelas',
    pill: 'Timer Kelas',
    excerpt: 'Pengatur waktu untuk aktivitas atau ujian di kelas — bantu siswa mengelola waktu mereka sendiri, bukan cuma mengandalkan guru mengingatkan.',
    category: 'Alat Bantu Guru',
    date: '2026-07-21',
    content: [
      'Timer Kelas menampilkan hitungan mundur untuk aktivitas atau ujian, terlihat oleh seluruh kelas selama waktunya berjalan.',
      '## Manfaatnya',
      'Batas waktu yang terlihat jelas membantu siswa mengatur ritme mengerjakan sendiri, alih-alih terus bertanya "berapa menit lagi" atau kaget saat waktu tiba-tiba habis.',
      '## Kapan Sebaiknya Dipakai',
      'Cocok dipakai saat ulangan/kuis berbatas waktu, kerja kelompok dengan tenggat singkat, atau aktivitas permainan yang butuh elemen waktu untuk menjaga tempo.',
      '## Cara Memakainya Secara Efektif',
      'Umumkan durasi ke siswa sejak aktivitas dimulai (jangan mendadak), dan tampilkan timer di layar yang bisa dilihat semua siswa supaya mereka bisa memantau sisa waktu sendiri tanpa terus bertanya ke guru.',
      '## Contoh & Kondisi Penggunaan',
      'Ulangan harian berdurasi 40 menit ditampilkan lewat Timer Kelas di layar proyektor, sehingga siswa bisa mengatur sendiri berapa lama mengerjakan tiap bagian soal tanpa harus bertanya sisa waktu ke guru.',
    ],
  },
  {
    slug: 'tool-papan-poin',
    title: 'Papan Poin Kelas — Bikin Kelas Lebih Hidup Lewat Kompetisi Sehat',
    pill: 'Papan Poin Kelas',
    excerpt: 'Papan skor gamifikasi untuk memotivasi partisipasi siswa — bikin kelas lebih hidup lewat kompetisi yang sehat.',
    category: 'Alat Bantu Guru',
    date: '2026-07-22',
    content: [
      'Papan Poin Kelas menampilkan skor kelompok atau individu secara real-time, dipakai untuk aktivitas yang melibatkan kompetisi atau sistem reward.',
      '## Manfaatnya',
      'Elemen kompetisi dan skor yang terlihat langsung sering meningkatkan partisipasi siswa yang biasanya pasif — mereka jadi lebih terdorong ikut aktif karena kontribusinya langsung terlihat berpengaruh ke skor.',
      '## Kapan Sebaiknya Dipakai',
      'Berguna untuk kompetisi antar kelompok dalam satu sesi pelajaran, program reward partisipasi jangka panjang sepanjang semester, atau aktivitas kuis yang butuh elemen skor untuk menjaga semangat.',
      '## Cara Memakainya Secara Efektif',
      'Tetapkan aturan poin yang jelas sejak awal dan konsisten dijalankan — perubahan aturan di tengah jalan (apalagi yang terkesan sepihak) bisa membuat siswa merasa sistemnya tidak adil.',
      '## Contoh & Kondisi Penggunaan',
      'Sepanjang satu semester, guru menjalankan kompetisi poin antar kelompok di mana tiap partisipasi aktif dan tugas selesai tepat waktu menambah poin. Papan Poin Kelas membuat progres tiap kelompok terlihat jelas dan mendorong semangat berkelanjutan, bukan cuma di awal saja.',
    ],
  },
  {
    slug: 'tool-presensi-digital',
    title: 'Presensi Digital — Absen Rapi Tanpa Kertas dan Hitung Manual',
    pill: 'Presensi Digital',
    excerpt: 'Absensi harian tanpa kertas, tersimpan rapi di perangkat yang dipakai — memudahkan rekap kehadiran periodik tanpa hitung manual.',
    category: 'Alat Bantu Guru',
    date: '2026-07-23',
    content: [
      'Presensi Digital mencatat kehadiran siswa harian langsung dari perangkat guru, tanpa perlu buku absen kertas yang mudah hilang atau rusak.',
      '## Manfaatnya',
      'Absensi kertas rawan hilang, sobek, atau susah direkap ulang di akhir bulan. Presensi digital membuat data kehadiran lebih rapi dan siap dipakai kapan pun dibutuhkan, tanpa perlu menghitung ulang secara manual.',
      '## Kapan Sebaiknya Dipakai',
      'Dipakai rutin di setiap awal kelas untuk mencatat kehadiran harian, sekaligus jadi sumber data saat perlu rekap kehadiran mingguan atau bulanan.',
      '## Cara Memakainya Secara Efektif',
      'Jadikan kebiasaan mengisi presensi tiap hari tanpa terlewat — datanya baru benar-benar berguna kalau lengkap dan konsisten, karena dari situ bisa terlihat pola kehadiran siswa dari waktu ke waktu.',
      '## Contoh & Kondisi Penggunaan',
      'Menjelang rapat wali murid, wali kelas perlu laporan kehadiran satu bulan terakhir untuk tiap siswa. Karena presensi dicatat digital tiap hari, rekap itu tinggal dilihat langsung tanpa perlu menghitung ulang dari buku absen manual.',
    ],
  },
  {
    slug: 'tool-generator-sertifikat',
    title: 'Sertifikat — Cetak Piagam Penghargaan Tanpa Perlu Jago Desain',
    pill: 'Sertifikat',
    excerpt: 'Buat sertifikat atau piagam penghargaan siswa dengan cepat dan rapi, tanpa perlu keahlian desain.',
    category: 'Alat Bantu Guru',
    date: '2026-07-24',
    content: [
      'Generator Sertifikat membuat sertifikat atau piagam penghargaan siap cetak, tanpa perlu membuka aplikasi desain grafis terpisah.',
      '## Manfaatnya',
      'Apresiasi yang diberikan dalam bentuk fisik/formal (bukan cuma ucapan lisan) lebih berkesan bagi siswa, tapi mendesainnya manual butuh waktu dan keahlian yang tidak semua guru punya. Tool ini menutup gap itu.',
      '## Kapan Sebaiknya Dipakai',
      'Cocok dipakai di akhir semester, acara perpisahan, penutupan lomba kelas, atau kapan pun guru ingin memberi apresiasi formal — baik untuk prestasi maupun sekadar partisipasi aktif.',
      '## Cara Memakainya Secara Efektif',
      'Personalisasi tiap sertifikat dengan nama dan pencapaian spesifik siswa, bukan sekadar template kosong yang sama untuk semua — sertifikat yang terasa "dibuat khusus" untuk siswa itu jauh lebih bermakna.',
      '## Contoh & Kondisi Penggunaan',
      'Di acara perpisahan kelas, guru ingin tiap siswa membawa pulang kenang-kenangan formal, bukan cuma untuk juara kelas. Generator Sertifikat memungkinkan tiap siswa mendapat sertifikat partisipasi yang dipersonalisasi tanpa guru harus mendesain satu-satu.',
    ],
  },
  {
    slug: 'tool-text-to-speech',
    title: 'Baca Teks (TTS) — Ubah Bacaan Jadi Audio untuk Siswa Auditori',
    pill: 'Baca Teks (TTS)',
    excerpt: 'Ubah teks atau cerita jadi audio — bantu variasi metode belajar sekaligus mendukung siswa dengan gaya belajar auditori.',
    category: 'Alat Bantu Guru',
    date: '2026-07-25',
    content: [
      'Baca Teks (Text-to-Speech) mengubah teks tertulis menjadi audio yang bisa diputar di kelas, berguna untuk cerita, bacaan, atau materi panjang lainnya.',
      '## Manfaatnya',
      'Tidak semua siswa menyerap informasi paling baik lewat membaca sendiri — sebagian lebih terbantu mendengar. TTS memberi variasi metode penyampaian materi tanpa guru harus membacakan sendiri dari awal sampai akhir.',
      '## Kapan Sebaiknya Dipakai',
      'Berguna untuk bacaan atau cerita panjang, latihan listening di kelas bahasa, atau untuk siswa dengan kebutuhan belajar yang lebih terbantu lewat audio dibanding teks visual saja.',
      '## Cara Memakainya Secara Efektif',
      'Kombinasikan audio dengan teks tertulis yang bisa diikuti siswa secara bersamaan — mendengar sambil membaca lebih efektif memperkuat pemahaman dibanding hanya mendengar saja.',
      '## Contoh & Kondisi Penggunaan',
      'Di kelas Bahasa Indonesia, guru ingin siswa fokus menyimak alur cerita pendek tanpa dirinya harus membacakan sambil menjaga intonasi selama 10 menit. Cerita diputar lewat TTS sementara siswa mengikuti teksnya, lalu dilanjutkan diskusi.',
    ],
  },
  {
    slug: 'tool-catatan-siswa',
    title: 'Catatan Siswa — Rekam Jejak Siswa, Bukan Cuma Mengandalkan Ingatan',
    pill: 'Catatan Siswa',
    excerpt: 'Dokumentasi perkembangan dan perilaku siswa secara individual — rekam jejak konkret, bukan cuma mengandalkan ingatan guru.',
    category: 'Alat Bantu Guru',
    date: '2026-07-26',
    content: [
      'Catatan Siswa menyimpan catatan perkembangan dan perilaku tiap siswa secara individual, bisa diakses kembali kapan pun dibutuhkan.',
      '## Manfaatnya',
      'Mengandalkan ingatan saja untuk melacak perkembangan puluhan siswa sepanjang semester itu sulit dan rawan bias (biasanya yang paling diingat cuma insiden besar). Catatan yang terdokumentasi memberi gambaran yang lebih lengkap dan adil.',
      '## Kapan Sebaiknya Dipakai',
      'Idealnya dipakai sepanjang semester secara berkala, bukan cuma saat ada insiden — termasuk mencatat perkembangan positif, bukan cuma masalah perilaku.',
      '## Cara Memakainya Secara Efektif',
      'Catat secara rutin dan singkat (tidak perlu panjang), segera setelah observasi terjadi supaya detailnya masih akurat. Catatan yang ditunda biasanya jadi kabur dan kurang berguna saat benar-benar dibutuhkan.',
      '## Contoh & Kondisi Penggunaan',
      'Menjelang rapat wali murid, guru perlu menjelaskan perkembangan seorang siswa yang sempat mengalami penurunan performa di pertengahan semester. Dengan catatan yang terdokumentasi rutin, guru bisa menunjukkan pola konkret alih-alih hanya mengandalkan kesan umum.',
    ],
  },
  {
    slug: 'tool-kalkulator-nilai',
    title: 'Kalkulator Nilai — Rata-Rata & KKM Otomatis, Bebas Salah Hitung',
    pill: 'Kalkulator Nilai',
    excerpt: 'Hitung rata-rata nilai berbobot dan status ketuntasan (KKM) secara otomatis — cepat dan bebas dari salah hitung manual.',
    category: 'Alat Bantu Guru',
    date: '2026-07-27',
    content: [
      'Kalkulator Nilai menghitung nilai akhir dari beberapa komponen dengan bobot berbeda (tugas, UTS, UAS), sekaligus menentukan status ketuntasan berdasarkan KKM.',
      '## Manfaatnya',
      'Menghitung nilai berbobot secara manual untuk satu kelas penuh rawan salah hitung, apalagi kalau komponennya banyak. Kalkulator otomatis memastikan hasilnya konsisten untuk semua siswa dan langsung menunjukkan siapa yang belum tuntas.',
      '## Kapan Sebaiknya Dipakai',
      'Paling terasa manfaatnya saat rekap nilai akhir semester dengan banyak komponen berbobot berbeda, atau kapan pun guru perlu cek cepat siapa saja yang belum mencapai KKM untuk tindak lanjut remedial.',
      '## Cara Memakainya Secara Efektif',
      'Pastikan bobot tiap komponen nilai (tugas, UTS, UAS) dimasukkan dengan benar sebelum menghitung untuk seluruh kelas — kesalahan bobot di awal akan mempengaruhi hasil akhir semua siswa sekaligus.',
      '## Contoh & Kondisi Penggunaan',
      'Nilai akhir satu mapel dihitung dari 20% tugas, 30% UTS, dan 50% UAS untuk 30 siswa. Kalkulator Nilai menghitung semuanya sekaligus dan langsung menandai siswa yang nilainya di bawah KKM untuk didata sebagai kandidat remedial.',
    ],
  },
  {
    slug: 'tool-ice-breaker',
    title: 'Ice Breaker — Pecahkan Ketegangan Kelas dengan Ice Breaker Seru',
    pill: 'Ice Breaker',
    excerpt: 'Ide game dan energizer singkat untuk mencairkan suasana kelas yang lesu atau tegang, tanpa memotong banyak waktu materi.',
    category: 'Alat Bantu Guru',
    date: '2026-07-28',
    content: [
      'Ice Breaker memberi ide permainan atau aktivitas energizer singkat yang bisa langsung dipakai untuk mengembalikan fokus dan semangat siswa.',
      '## Manfaatnya',
      'Kelas yang lesu (misalnya siang hari setelah makan siang) atau tegang (menjelang ujian) sulit menyerap materi baru dengan baik. Ice breaker singkat membantu mereset suasana sebelum melanjutkan pelajaran, tanpa perlu guru memikirkan ide dadakan sendiri.',
      '## Kapan Sebaiknya Dipakai',
      'Cocok dipakai di awal kelas setelah istirahat, jam pelajaran siang yang biasanya bikin mengantuk, atau sebelum masuk ke materi yang berat dan butuh konsentrasi penuh.',
      '## Cara Memakainya Secara Efektif',
      'Batasi durasinya (biasanya cukup 3–5 menit) supaya tidak memotong banyak waktu materi, dan pilih aktivitas yang sesuai usia serta karakter kelas — yang cocok untuk kelas rendah SD belum tentu cocok untuk siswa SMA.',
      '## Contoh & Kondisi Penggunaan',
      'Jam pelajaran pertama setelah makan siang biasanya kelas terasa mengantuk dan sulit fokus. Ice breaker singkat 3 menit sebelum masuk materi membantu siswa lebih segar dan siap menerima pelajaran, dibanding langsung memaksakan masuk ke topik berat.',
    ],
  },
];

export function getArticleBySlug(slug: string): BlogArticle | undefined {
  return BLOG_ARTICLES.find((a) => a.slug === slug);
}
